apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar-config
  namespace: default
data:
  # Standalone configuration for development
  standalone.conf: |
    # Enable the WebSocket service
    webSocketServiceEnabled=true
    # Enable the Pulsar proxy
    httpServerEnabled=true
    # Number of IO threads
    numHttpServerThreads=8
    # Disable authentication for development
    authenticationEnabled=false
    authorizationEnabled=false
    # Enable non-persistent topics
    enableNonPersistentTopics=true
    # Reduce resource usage for development
    managedLedgerDefaultEnsembleSize=1
    managedLedgerDefaultWriteQuorum=1
    managedLedgerDefaultAckQuorum=1